sudo: required

language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
    - docker build -t holochain/clutter -f Dockerfile.travis .;
    - docker run -d --name website -p 3141:3141 holochain/clutter /bin/sh -c "cd /go/bin; hcdev init -cloneExample=clutter -fromBranch=$TRAVIS_BRANCH; cd clutter; hcdev web 3141;"

script:
      - cd ui-automation
      - npm install
      - npm test
      - docker kill website

cache:
  directories:
    - node_modules
