sudo: required

language: node_js
node_js:
  - "8"

env:
  - DOCKER_COMPOSE_VERSION=1.18.0

services:
  - docker

before_install:
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin

script:
  - cd ui-src
  - yarn install
  - yarn build
  - TARGETDIR=$(pwd) docker-compose up -d
  - cd ui-automation
  - npm install
  - npm test
  - docker-compose kill
  - docker-compose down

cache:
  directories:
    - ui-automation/node_modules
