sudo: required

language: go
go:
  - 1.8

services:
  - docker

before_install:
    - docker build -t holochain/clutter -f Dockerfile.travis .;
    - docker run --rm -ti -p 3141:3141 holochain/clutter -c "cd /go/bin; hcdev init -cloneExample=clutter -fromBranch=$TRAVIS_BRANCH; cd clutter; hcdev web 3141;"
