sudo: required
language: node_js
node_js:
- '8'
env:
  matrix:
  - DOCKER_COMPOSE_VERSION=1.18.0

services:
- docker
before_install:
- cd ui-src
- yarn install
- yarn build
- cd ..
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- TARGETDIR=$(pwd) docker-compose up -d
script:
- cd ui-automation
- npm install
- npm test
- cd ..
- cd ui-src
- npm release:files
- docker-compose kill
- docker-compose down
cache:
  directories:
  - ui-automation/node_modules


deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file_glob: true
  file: release/*
  skip_cleanup: true
  on:
    branch: master
    tags: true
