[workspace]
resolver = "2"
members = [
    "dnas/clutter/zomes/profiles",
    "dnas/clutter/zomes/mews",
    "dnas/clutter/zomes/index_stub",
    "dnas/clutter/zomes/filestore",
    "dnas/clutter/zomes/pathlinks",
    "dnas/clutter_index/zomes/index",
    "dnas/clutter_index/zomes/services",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
