[package]
edition = "2018"
name = "follow"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "follow"

[dependencies]
serde = "1"
derive_more = "0"
profiles = { path = "../../profiles" }

hdk = {version = "0.0.120", features = ["encoding"]}